#!/bin/bash
g++ -g -DLOCAL -Wall -Wextra -Wshadow zen.cpp -o zen
g++ -g -DLOCAL -Wall -Wextra -Wshadow asn.cpp -o asn
g++ -g -DLOCAL -Wall -Wextra -Wshadow brute.cpp -o brute

for i in `seq 1 100`; do
  # ...argv example: $i 1 2 "a"...etc [any string]
  ulimit -s unlimited && ulimit -v unlimited && ./zen ...argv >zen_in
  ulimit -s unlimited && ulimit -v unlimited && ./asn <zen_in >zen_out
  ulimit -s unlimited && ulimit -v unlimited && ./brute <zen_in >zen_ans
  
  # diff zen_out zen_ans || break
  DIFF=$(diff zen_out zen_ans) 
  if [ "$DIFF" ] 
  then
    echo "tc : $i Wrong Answer"
    echo "input >> "
    cat zen_in
    echo
    echo "output >>"
    cat zen_out
    echo
    echo "answer >>"
    cat zen_ans
    break
  else
    echo "tc : $i Accepted"
  fi
done

rm -f ./zen
rm -f ./asn
rm -f ./brute

